Vagrant.configure("2") do |config|
  config.vm.define :win7, autostart: false do |win7|
    win7.vm.box = "cheretbe/win7_ru_64"
    win7.winrm.username = "vagrant"
    win7.winrm.password = "#{ENV['AO_DEFAULT_VAGRANT_PASSWORD']}"
    win7.vm.boot_timeout = 600
    win7.vm.hostname = "win7"
    win7.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end
    win7.vm.network "private_network", ip: "192.168.200.20", virtualbox__intnet: "vagrant-intnet"
    win7.vm.provision "shell", name: "Install Zabbix agent", keep_color: true,
      path: "provision-script.ps1"
  end

  config.vm.define :win10, autostart: false do |win10|
    win10.vm.box = "cheretbe/win10_ru_64"
    win10.winrm.username = "vagrant"
    win10.winrm.password = "#{ENV['AO_DEFAULT_VAGRANT_PASSWORD']}"
    win10.vm.boot_timeout = 600
    win10.vm.hostname = "win10"
    win10.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end
    win10.vm.network "private_network", ip: "192.168.200.21", virtualbox__intnet: "vagrant-intnet"
    win10.vm.provision "shell", name: "Install Zabbix agent", keep_color: true,
      path: "provision-script.ps1"
  end
end