Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    # prevent 'ubuntu-xenial-16.04-cloudimg-console.log' file creation
    # https://groups.google.com/forum/#!topic/vagrant-up/eZljy-bddoI
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]

    config.vm.synced_folder "../../saltstack/", "/srv"
    config.vm.synced_folder "../../../", "/multi-ip-ddclient"
  end
  config.vm.hostname = "template-editor"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # config.vm.provision "shell", name: "python-pygit2 installation", keep_color: true,
  #   inline: "apt-get -y -q update && apt-get -y -q install python-pygit2"

  config.vm.provision :salt do |salt|
    salt.minion_config = "./saltstack_minion"
    salt.masterless = true
    salt.run_highstate = true
    salt.install_type = "stable"
    salt.verbose = true
  end
end