zabbix_version = "4.0"
if File.file?("local-config.yml")
  local_config = YAML.load_file("local-config.yml")
  unless local_config.nil?
    zabbix_version = local_config.fetch("zabbix_version", zabbix_version)
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    # prevent 'ubuntu-xenial-16.04-cloudimg-console.log' file creation
    # https://groups.google.com/forum/#!topic/vagrant-up/eZljy-bddoI
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]

    config.vm.synced_folder "../../../", "/zabbix-templates"
  end
  config.vm.hostname = "template-editor"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.200.10", virtualbox__intnet: "vagrant-intnet"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/provision.yml"
    ansible.compatibility_mode = "2.0"
    ansible.extra_vars = {
      # "ansible_python_interpreter": "/usr/bin/python3",
      "zabbix_repo_version": zabbix_version
    }
  end
end